# action.yml
name: 'Terraform Action'
author: 'Thomas Pisula'
description: 'Execute Terraform as Github Action.'
inputs:
  chdir:
    description: 'Path to pass to -chdir.'
    required: false
  init:
    description: 'Exec terraform init prior to terraform commands (yes, no).'
    required: false
    default: yes
  varsFile:
    description: 'The vars file to use.'
    required: false
  planFile:
    description: 'The plan file to use.'
    required: false
  backendConfigFile:
    description: 'The backend config file to use.'
    required: false
  verb:
    description: 'The terraform verb to use.'
    required: false
    default: 'apply'
  sshKey:
    description: 'The sshKey to use for host connections.'
    required: false
outputs:
  terraformVersion: 
    description: 'The version of terraform used.'
runs:
  using: docker
  image: docker://docker.io/labratswork/action-terraform:latest
  args:
    - ${{ inputs.chdir }}
    - ${{ inputs.init }}
    - ${{ inputs.backendConfigFile }}
    - ${{ inputs.varsFile }}
    - ${{ inputs.planFile }}
    - ${{ inputs.verb }}
    - ${{ inputs.sshKey }}
branding:
  icon: 'cloud-lightning'
  color: 'purple'