# action.yml
name: 'Terraform Action'
author: 'Thomas Pisula'
description: 'Execute Terraform as Github Action.'
inputs:
  workingDirectory:
    description: 'Changes the working directory prior to execution of terraform commands.'
    required: false
  init:
    description: 'Exec terraform init prior to terraform commands (yes, no).'
    required: false
  varsFile:
    description: 'The vars file to use.'
    required: false
  planFile:
    description: 'The plan file to use.'
    required: false
  verb:
    description: 'The terraform verb to use.'
    required: false
    default: 'apply'
  sshKey:
    description: 'The sshKey to use for host connections.'
    required: false
outputs:
  terraformVersion: 
    description: 'The version of terraform used.'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.workingDirectory }}
    - ${{ inputs.init }}
    - ${{ inputs.varsFile }}
    - ${{ inputs.planFile }}
    - ${{ inputs.verb }}
    - ${{ inputs.sshKey }}